### ISSUE TITLE
NV hangs when Z3 returns unexpected answer

### ISSUE THREAD

**Issue by nickgian** [NetworkVerification/nv#23]
For instance if Z3 returns an error then NV hangs and doesn't display anything.
We should adjust the behavior such that the error message gets propagated and the program terminated.

**Comment by DKLoehr** [comment]
Do you have a particular example that displays this?

**Comment by nickgian** [comment]
Um not of the top of my head. I faced this issue when I made a mistake in the SMT encoding causing Z3 to return an error message and NV would just hang leaving me to wonder what was going on.
