### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by alberdingk-thijm** [NetworkVerification/nv#47]
This issue is intended as a place where we can discuss possible new and witty names for the project, as the current name is a bit bland.

Each idea should get its own comment so we can react to it.
Feel free to add some justification behind your name if you think it needs any.

**Comment by alberdingk-thijm** [comment]
NV is the postal acronym for [Nevada](https://en.wikipedia.org/wiki/Nevada), so we could potentially have a fun name taken from Nevadan geography.

I'm already breaking my own suggestion to give each idea its own comment, but since these are all fairly related, I'll just put them together. If we like any of them, I'll add a separate comment below.

- Nevada
- Vegas
- Sagebrush (state flower)

**Comment by DKLoehr** [comment]
Owlshark. Needs no justification.

**Comment by alberdingk-thijm** [comment]
[Araneid](https://en.wikipedia.org/wiki/Orb-weaver_spider) or Aranet, after the spiders which weave orb webs. They can use vibrations in the web to detect bugs that get caught.

**Comment by alberdingk-thijm** [comment]
Akash's suggestion: Spiderweb (similar idea to above)

**Comment by Anonymous-Stranger** [comment]
Antlion -- play on batfish, also catches bugs.
