### ISSUE TITLE
Give nodes name identifiers instead of numbers

### ISSUE THREAD

**Issue by DKLoehr** [NetworkVerification/nv#57]
It would be handy to give nodes names instead of numbers, for ease of use. This would let 
programmers identify nodes more easily when looking at or writing nv programs.

One way to do this would be to optionally declare a mapping of node values to identifiers at the beginning of the program. To distinguish node values from other identifiers, we could specify that node values begin with a capital letter.

**Comment by DKLoehr** [comment]
This is potentially related to #58, since we might view the node identifiers as something similar to an enum variant type.

**Comment by alberdingk-thijm** [comment]
Think this overlaps with #48. Should we close one of them?
