### ISSUE TITLE
cudd error when installing nv

### ISSUE THREAD

**Issue by bkv2chu** [NetworkVerification/nv#61]
following instructions in readme to install nv. when I run make, terminates with an error:
```
Undefined symbols for architecture x86_64:
  "_caml_stat_compactions", referenced from:
      _Cuddaux_addCamlConst in libcudd_caml.a(cuddauxAddCamlTable.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
File "caml_startup", line 1:
Error: Error during linking
make: *** [default] Error 1
```

**Comment by DKLoehr** [comment]
Possibly related to #7, but this is a different error, and the solution provided for that issue doesn't work here. I'm trying to replicate this on one of my computers.

**Comment by bkv2chu** [comment]
This issue was resolved by reverting to an earlier ocaml (specifically ocaml 1.06.0). This was done with the command
'''opam switch create 4.06.0'''

**Comment by nickgian** [comment]
fyi mlcuddidl has been updated on OPAM and is now compatible with OCaml >= 4.10.0.
